### ISSUE TITLE
为什么todo 里面要toggle 方法 & donate 网址出错了

### ISSUE THREAD

**Issue by pasicopan** [the5fire/backbonejs-learning-note#28]
为什么todo 里面要toggle 方法，
TodoView 里面的toggleDone 方法也可以承担这样的功能啊，例如改成这样：
toggleDone:function(){
      this.model.save({done: !this.model.get('done')});
    },

**Comment by the5fire** [comment]
当然也可以，只不过是在合适的地方做而已。

你可以把toggle理解为todo的一个行为

**Comment by pasicopan** [comment]
明白了，thanks
