### ISSUE TITLE
- _下划线问题

### ISSUE THREAD

**Issue by ymdshxjj** [the5fire/backbonejs-learning-note#36]
<ul id="world-list">
    </ul>

建议把world-list 改成world_list，代码手抄下来，这个东西坑了好久。

**Comment by the5fire** [comment]
怎么个坑法？

**Comment by mhxy13867806343** [comment]
world-list  world_list  World_List之类的我都用

**Comment by the5fire** [comment]
命名之类的就看要遵循什么规范了。中横线，驼峰，下划线都可以，不过还是建议参考前端编码规范。
